server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ecommercebase

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jwt:
    key: mOUjM9gfE8+PffkSkrGE8tMxajYk7eD3T98YpMFjGSzsTGB5f4/WpqhBKifDcIHu
    access-duration: 86400
    refresh-duration: 604800

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false
      key-serializer:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"

  data:
    redis:
      host: 172.24.64.1
      port: 6379

logging:
  level:
    org:
      springframework:
        data:
          redis:
            DEBUG
        security:
          web:
            access: DEBUG
            authentication: DEBUG




